version: "3.8"

# docker network create -d bridge backend-teamcity
networks:
  backend-teamcity:
    external: true
    name: backend-teamcity

services:
  nginx-tc:
    image: nginx:1.15-alpine
    container_name: nginx-tc
    restart: unless-stopped
    volumes:
      - /app/nginx.conf:/etc/nginx/nginx.conf:ro
      - /data/ssl:/etc/nginx/certs
      - /app/static:/app/static
    ports:
      - "80:80"
      - "443:443"
      - "1433:1433"
    networks:
      - backend-teamcity

  teamcity:
    image: jetbrains/teamcity-server:2023.05.2
    container_name: teamcity
    restart: unless-stopped
    volumes:
      - /data/teamcity/datadir:/data/teamcity_server/datadir
      - /data/teamcity/log:/opt/teamcity/logs
    networks:
      - backend-teamcity
    user: "root"
    environment:
      - TEAMCITY_HTTPS_PROXY_ENABLED=true
      - TEAMCITY_SERVER_MEM_OPTS=-Xmx2g -XX:ReservedCodeCacheSize=350m
